apiVersion: 1

deleteDatasources:
  - name: "FROST-Server - v1.1"

datasources:
- name: "FROST-Server - v1.1"
  type: linksmart-sensorthings-datasource
  access: proxy
  url: http://frost-web:8080/FROST-Server/v1.1
  isDefault: true
  editable: true
